Add activation loop

diff --git a/.github/actions/cubit_setup/action.yml b/.github/actions/cubit_setup/action.yml
--- a/.github/actions/cubit_setup/action.yml
+++ b/.github/actions/cubit_setup/action.yml
@@ -10,6 +10,10 @@ inputs:
   cubit_password:
     description: Password to activate cubit
     required: true
+  cubit_activation_timeout:
+    description: Timeout to try cubit activation in seconds
+    required: false
+    default: "300"
 outputs:
   cubit_root:
     description: "Path to the Cubit installation"
@@ -37,5 +41,25 @@ runs:
         CUBIT_FOLDER=$(find . -maxdepth 1 -type d -name "Coreform-Cubit-*" | head -n 1 | sed 's|^\./||')
         CUBIT_ROOT="$(pwd)/$CUBIT_FOLDER"
         echo "cubit_root=$CUBIT_ROOT" >> "$GITHUB_OUTPUT"
-        # Activate cubit
-        $CUBIT_ROOT/bin/rlm_activate --login ${{ inputs.cubit_email }} ${{ inputs.cubit_password }}
+        # Activate cubit. Retry login until success or timeout.
+        timeout="${{ inputs.cubit_activation_timeout }}"
+        start=$(date +%s)
+        while true; do
+          $CUBIT_ROOT/bin/rlm_activate --login ${{ inputs.cubit_email }} ${{ inputs.cubit_password }}
+          status=$?
+
+          if [ $status -eq 0 ]; then
+            echo "Cubit activation succeeded."
+            break
+          fi
+
+          now=$(date +%s)
+          elapsed=$(( now - start ))
+          if [ $elapsed -ge $timeout ]; then
+            echo "Cubit activation timeout reached after $elapsed seconds."
+            break
+          fi
+
+          # Delay between retries.
+          sleep 5
+        done
